# Generated by Django 5.0.4 on 2024-05-01 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Electronics', 'Electronics'), ('Apparel', 'Apparel'), ('Home Appliances', 'Home Appliances'), ('Health & Wellness', 'Health & Wellness'), ('Home Improvement', 'Home Improvement')], help_text='Enter the name of the author', max_length=100, verbose_name='Author name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the product', max_length=100, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price of the product', max_digits=6, verbose_name='Price')),
                ('stock', models.IntegerField(help_text='Enter the stock of the product', verbose_name='Stock')),
                ('category', models.ForeignKey(help_text='Enter the category of the product', on_delete=django.db.models.deletion.CASCADE, to='rest_app.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
