# Generated by Django 5.0.4 on 2024-05-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(choices=[('Electronics', 'Electronics'), ('Apparel', 'Apparel'), ('Home Appliances', 'Home Appliances'), ('Health & Wellness', 'Health & Wellness'), ('Home Improvement', 'Home Improvement')], help_text='Enter the category of the product', on_delete=django.db.models.deletion.CASCADE, to='rest_app.category', verbose_name='Category'),
        ),
    ]
