# Generated by Django 5.0.4 on 2024-05-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Apparel', 'Apparel'), ('Home Appliances', 'Home Appliances'), ('Health & Wellness', 'Health & Wellness'), ('Home Improvement', 'Home Improvement')], help_text='Enter the name of the category', max_length=100, verbose_name='Author name'),
        ),
    ]
