# Generated by Django 5.0.4 on 2024-05-01 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0004_alter_category_name_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Enter the category of the product', null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_app.category', verbose_name='Category'),
        ),
    ]
