# Generated by Django 5.0.4 on 2024-05-01 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Apparel', 'Apparel'), ('Home Appliances', 'Home Appliances'), ('Health & Wellness', 'Health & Wellness'), ('Home Improvement', 'Home Improvement')], help_text='Enter the name of the category', max_length=100, verbose_name='Author name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, choices=[('Electronics', 'Electronics'), ('Apparel', 'Apparel'), ('Home Appliances', 'Home Appliances'), ('Health & Wellness', 'Health & Wellness'), ('Home Improvement', 'Home Improvement')], help_text='Enter the category of the product', null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_app.category', verbose_name='Category'),
        ),
    ]
