# Generated by Django 5.0.4 on 2024-05-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Electronics', 'Electronics and Gadgets'), ('Clothes', 'Clothes and Shoes'), ('Home', 'Home Supplies')], help_text='Enter the name of the category', max_length=100, verbose_name='Author name'),
        ),
    ]
